// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default (req, res) => {
  res.statusCode = 200;
  res.json({
    status: 'OK',
    data: [
      {
        assignName: 'nam.pham123@thuocsi.vn',
        assignUser: 684,
        bankAccountName: 'Dung',
        bankBranch: 'HCM',
        bankCode: '123432',
        bankName: 'Techcom',
        cashback: 0,
        chatURL: '',
        code: 'E1U2U2',
        createdBy: 'dat.le1@thuocsi.vn',
        createdByType: 'EMPLOYEE',
        createdTime: '2021-03-26T04:12:27.623Z',
        customerCode: 'QK66666666',
        customerID: 664,
        departmentCode: 'HN',
        facebookURL: '',
        feedBackContent: '',
        imageUrls: [],
        lastUpdatedTime: '2021-03-26T06:35:02.446Z',
        note: '',
        reasons: ['SAI_SAN_PHAM', 'CHENH_LECH_CHUYEN_KHOAN', 'DONG_THIEU_HANG'],
        returnCode: '',
        saleOrderCode: 'L42AXHR2',
        saleOrderID: 407,
        status: 'PENDING',
      },
      {
        assignName: 'thaotran',
        assignUser: 465,
        bankAccountName: 'Dung cái gì mà Dung',
        bankBranch: 'HCM',
        bankCode: '123432',
        bankName: 'Techcom',
        cashback: 100000,
        chatURL: 'http://messenger.com/thuocsi_test01',
        code: 'WEV3PA',
        createdBy: 'nam.pham@thuocsi.vn',
        createdByType: 'EMPLOYEE',
        createdTime: '2021-03-25T09:29:02.142Z',
        customerCode: 'QK66666666',
        customerID: 664,
        departmentCode: 'MKT',
        facebookURL: 'https://facebook.com/thuocsi_test01',
        feedBackContent: 'phản hồi test 01',
        imageUrls: [],
        lastUpdatedTime: '2021-03-26T06:37:01.347Z',
        note: 'mô tả test 01',
        reasons: ['DONG_THIEU_HANG'],
        returnCode: 'MAHANGTEST01',
        saleOrderCode: 'L42AXHR2',
        saleOrderID: 408,
        status: 'ASSIGNED',
      },
      {
        assignName: 'Nguyen Thien Vuong',
        assignUser: 29,
        bankAccountName: 'Dung',
        bankBranch: 'HCM',
        bankCode: '123432',
        bankName: 'Techcom',
        cashback: 0,
        chatURL: '',
        code: 'QX7GBK',
        createdBy: 'nam.pham@thuocsi.vn',
        createdByType: 'EMPLOYEE',
        createdTime: '2021-03-25T09:28:17.459Z',
        customerCode: 'QK66666666',
        customerID: 664,
        departmentCode: 'TECH',
        facebookURL: '',
        feedBackContent: '',
        imageUrls: [],
        lastUpdatedTime: '2021-03-25T09:28:39.839Z',
        note: '',
        reasons: ['SAI_SAN_PHAM'],
        returnCode: '',
        saleOrderCode: 'L42AXHR2',
        saleOrderID: 409,
        status: 'DONE',
      },
      {
        assignName: 'nam.pham@thuocsi.vn',
        assignUser: 999999,
        bankAccountName: 'Dung',
        bankBranch: 'HCM',
        bankCode: '123432',
        bankName: 'Techcom',
        cashback: 0,
        chatURL: '',
        code: 'BDCLT1',
        createdBy: 'nam.pham@thuocsi.vn',
        createdByType: 'EMPLOYEE',
        createdTime: '2021-03-25T09:27:47.959Z',
        customerCode: 'QK66666666',
        customerID: 664,
        departmentCode: 'FULFILLMENT',
        facebookURL: '',
        feedBackContent: '',
        imageUrls: [],
        lastUpdatedTime: '2021-03-25T09:27:47.959Z',
        note: '',
        reasons: ['SAN_PHAM_HU_BE'],
        returnCode: '',
        saleOrderCode: 'L42AXHR2',
        saleOrderID: 415,
        status: 'CANCELLED',
      },
      {
        assignName: 'pickerhcm01',
        assignUser: 685,
        bankAccountName: 'Dung',
        bankBranch: 'HCM',
        bankCode: '123432',
        bankName: 'Techcom',
        cashback: 0,
        chatURL: '',
        code: 'VW6FV3',
        createdBy: 'nam.pham@thuocsi.vn',
        createdByType: 'EMPLOYEE',
        createdTime: '2021-03-25T09:25:28.905Z',
        customerCode: 'QK66666666',
        customerID: 664,
        departmentCode: 'HCM',
        facebookURL: '',
        feedBackContent: '',
        imageUrls: [],
        lastUpdatedTime: '2021-03-26T06:11:33.942Z',
        note: '',
        reasons: ['SAI_SAN_PHAM'],
        returnCode: '',
        saleOrderCode: 'L42AXHR2',
        saleOrderID: 432,
        status: 'IN_PROCESS',
      },
      // {
      //   id: '6',
      //   name: 'Hàng Mới',
      //   icon: 'fab fa-hotjar',
      //   redirectUrl: 'https://try.thuocsi.vn/daitiechangmoi',
      //   isNew: true
      // }
    ],
  });
};
