export default (req, res) => {
  res.statusCode = 200;
  res.json({
    status: 'OK',
    data: [
      {
        bankAccountName: 'Đạt LÊ',
        bankBranch: 'gia định',
        bankCode: '12313',
        bankName: 'ACB',
        code: 'H6GBKR',
        createdBy: '0353328060',
        createdByName: 'Dat Le',
        createdByType: 'CUSTOMER',
        createdTime: '2021-03-30T09:48:43.645Z',
        customerCode: 'H6HDUVQX',
        customerID: 1540,
        feedBackContent: 'nọi6 dung hơi sai sai',
        imageUrls: [],
        lastUpdatedTime: '2021-03-30T09:48:43.645Z',
        orderCode: 'H2GEQ1PG',
        reasons: ['SAI_SAN_PHAM', 'THAY_DOI_DIA_CHI'],
        saleOrderID: 443,
        status: 'PENDING',
      },
      {
        bankAccountName: 'Đạt LÊ',
        bankBranch: 'gia định',
        bankCode: '12313',
        bankName: 'ACB',
        code: 'H6GBKR',
        createdBy: '0353328060',
        createdByName: 'Dat Le',
        createdByType: 'CUSTOMER',
        createdTime: '2021-03-30T09:48:43.645Z',
        customerCode: 'H6HDUVQX',
        customerID: 1540,
        feedBackContent: 'nọi6 dung hơi sai sai',
        imageUrls: [],
        lastUpdatedTime: '2021-03-30T09:48:43.645Z',
        orderCode: 'H2GEQ1PG',
        reasons: ['SAI_SAN_PHAM', 'THAY_DOI_HINH_THUC_THANH_TOAN'],
        saleOrderID: 443,
        status: 'ASSIGNED',
      },
      {
        bankAccountName: 'Đạt LÊ',
        bankBranch: 'gia định',
        bankCode: '12313',
        bankName: 'ACB',
        code: 'H6GBKR',
        createdBy: '0353328060',
        createdByName: 'Dat Le',
        createdByType: 'CUSTOMER',
        createdTime: '2021-03-30T09:48:43.645Z',
        customerCode: 'H6HDUVQX',
        customerID: 1540,
        feedBackContent: 'nọi6 dung hơi sai sai',
        imageUrls: [],
        lastUpdatedTime: '2021-03-30T09:48:43.645Z',
        orderCode: 'H2GEQ1PG',
        reasons: ['TINH_TRANG_DON_HANG'],
        saleOrderID: 443,
        status: 'IN_PROCESS',
      },
      {
        bankAccountName: 'Đạt LÊ',
        bankBranch: 'gia định',
        bankCode: '12313',
        bankName: 'ACB',
        code: 'H6GBKR',
        createdBy: '0353328060',
        createdByName: 'Dat Le',
        createdByType: 'CUSTOMER',
        createdTime: '2021-03-30T09:48:43.645Z',
        customerCode: 'H6HDUVQX',
        customerID: 1540,
        feedBackContent: 'nọi6 dung hơi sai sai',
        imageUrls: [],
        lastUpdatedTime: '2021-03-30T09:48:43.645Z',
        orderCode: 'H2GEQ1PG',
        reasons: ['SAI_SAN_PHAM'],
        saleOrderID: 443,
        status: 'DONE',
      },
      {
        bankAccountName: 'Đạt LÊ',
        bankBranch: 'gia định',
        bankCode: '12313',
        bankName: 'ACB',
        code: 'H6GBKR',
        createdBy: '0353328060',
        createdByName: 'Dat Le',
        createdByType: 'CUSTOMER',
        createdTime: '2021-03-30T09:48:43.645Z',
        customerCode: 'H6HDUVQX',
        customerID: 1540,
        feedBackContent: 'nọi6 dung hơi sai sai',
        imageUrls: [],
        lastUpdatedTime: '2021-03-30T09:48:43.645Z',
        orderCode: 'H2GEQ1PG',
        reasons: ['SAI_SAN_PHAM'],
        saleOrderID: 443,
        status: 'CANCELLED',
      },
    ],
    message: 'Get customer successfully.',
  });
};
