export const API_HOST = process.env.API_HOST || '/backend';
export const MOCK_API_HOST = process.env.MOCK_API_HOST || '/api';
export const BASIC_AUTHEN = process.env.NEXT_PUBLIC_BASIC_AUTHEN || '';
export const DOMAIN_SELLER_CENTER = process.env.NEXT_PUBLIC_DOMAIN_SELLER_CENTER || '';
export const FACEBOOK_MESSENGER_ID = process.env.NEXT_PUBLIC_FACEBOOK_MESSENGER_ID || '';
export const DISCOVERY_URL = process.env.NEXT_PUBLIC_DISCOVERY || '';
export const NEXT_I18NEXT_NAME_SPACES = ['common', 'apiErrors'];
export const DOMAINT_TS = process.env.NEXT_PUBLIC_DOMAIN_TS || '';
export const ENV = process.env.NEXT_PUBLIC_ENV || 'stg';
